# Generated by Django 5.2.5 on 2025-09-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='publisehd',
            new_name='published',
        ),
    ]
