# Generated by Django 5.2.5 on 2025-09-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_publisehd_posts_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='miniature',
            field=models.ImageField(null=True, upload_to='posts/img/'),
        ),
    ]
