# Generated by Django 5.2.5 on 2025-09-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_posts_miniature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='posts/img/'),
        ),
    ]
